### ISSUE TITLE
Translations ?

### ISSUE THREAD

**Issue by lutinotmalin** [neversun/bodyweight-timer#11]
Hey !

I love your app on Sailfish OS and I use it everyday. I was planning to translate it to my main language (French) but I can't find any translations on the Code...

Are you going to pull a translatable file soon ? If so, don't hesitate to warn me !

Cheers,

**Comment by neversun** [comment]
I will prepare translations and enable you to translate it. Any recommendations @lutinotmalin?

**Comment by lutinotmalin** [comment]
Nice ! My only recommendation would be related to the platform. 

IMO, GitHub is ok but **Transifex** is a lot better regarding the translation thing. Very easy to edit strings, as the built-in editor is really simple to get through.

Furthermore, you could get more different languages if you decide to put your projet on Transifex :+1: Just advertise the community on Jolla Together and you should get your translations quickly !

**Comment by ghost** [comment]
You can also apply for hosting at Weblate: https://hosted.weblate.org/hosting/

Weblate is free software and they host free software projects for free. It also works better than Transifex.

**Comment by lutinotmalin** [comment]
Yeah I guess Weblate should do the job. However, I'm still on Transifex side, just because it seems to be the most popular platform, therefore carrying more translators.

**Comment by lutinotmalin** [comment]
Up ! Any news about Bodyweight Timer localization ? :)

**Comment by neversun** [comment]
Yeah. I got access to weblate last week.

I also had to fix some serious issues with my translation-file build-pipeline. But by yesterday I could fix all problems. Now I will just rewrite the existing app and put the files to weblate.

This should be happening the next days.

**Comment by lutinotmalin** [comment]
Wow that's great ! Thanks for your support ;-)

**Comment by neversun** [comment]
Feel free to add a translation: https://hosted.weblate.org/projects/bodyweight-timer-sailfish-os/ :smile:

**Comment by lutinotmalin** [comment]
OK, the French one is now done, but there were only 12 strings and I think there still are missing words (for example, the terms that are in the cover mode, or some words like "Settings"). Or perhaps they're translated automatically by Weblate, based on similarities ?

**Comment by ghost** [comment]
There seem to be a lot of empty <source> strings in https://github.com/neversun/bodyweight-timer/blob/master/translations/harbour-bodyweight-timer.ts

Which is probably why they don't show up in Weblate.

**Comment by lutinotmalin** [comment]
I see, it makes sense. I'll wait for the completed file then !

**Comment by neversun** [comment]
Ow. I think you might be right. I will provide a source to every string 👍

**Comment by neversun** [comment]
It will take some more time. Being quite busy this and the next week and having problems with fallback/source strings not showing up for non-translated languages :-1:

**Comment by lutinotmalin** [comment]
Take your time neversun, we're not in a hurry ! I'll be patient :+1:

**Comment by neversun** [comment]
I solved all the problems. All strings are visible at weblate but I had to revert all translations.
But I also saved and restored the complex strings (the explanations) from French and Dutch.

For reference, I attached the old translations
[bodyweight-timer-sailfish-os-translations-fr.xlsx](https://github.com/neversun/bodyweight-timer/files/1820795/bodyweight-timer-sailfish-os-translations-fr.xlsx)
[bodyweight-timer-sailfish-os-translations-nl.xlsx](https://github.com/neversun/bodyweight-timer/files/1820796/bodyweight-timer-sailfish-os-translations-nl.xlsx)



It would be nice if you could provide the missing translations. And yes, there are a lot of duplicate translation strings. I will fix it later on my own :smile:

**Comment by lutinotmalin** [comment]
All right, thanks for the files ! I'll take a look today on Weblate ! Sorry about the late.

**EDIT :** the French translation is finally done. The ball is on your side now ! :+1:

**Comment by neversun** [comment]
Added with 1.3.0. Submitted to Jolla Store
