### ISSUE TITLE
aarch64 version?

### ISSUE THREAD

**Issue by poetaster** [neversun/bodyweight-timer#15]
A number of people have asked on the forum. If you don't have time, I can push it to chum or set up a github action to build with coderus docker images here on github.

**Comment by neversun** [comment]
Thanks for reaching out. I will setup github actions and update the sailfish store.

**Comment by poetaster** [comment]
> Thanks for reaching out. I will setup github actions and update the sailfish store.

Cool! Thanks a lot!

**Comment by neversun** [comment]
I could finally upload the aarch64 binary to the Harbour store :)

**Comment by poetaster** [comment]
> I could finally upload the aarch64 binary to the Harbour store :)

Thanks a lot!
