### ISSUE TITLE
Order of property-assignments undefined, could lead to problems

### ISSUE THREAD

**Issue by LinuCC** [neversun/bodyweight-timer#2]
As written in [This stackoverflow post](http://stackoverflow.com/questions/25018821/is-the-order-of-function-calls-during-qml-object-initialization-deterministic), the order in which the properties are defined is not deterministic.
This could lead to a problem, for example in `Tabata.qml`:

``` qml
    property variant    value1ReturnFromDB:     DB.getDatabaseValuesFor(page,"value1")
    ...
    property int        value1:                 value1ReturnFromDB[0]
```

It is possible that the assignment of `value1` will be executed before `value1ReturnFromDB`, making `value1` undefined even if the database-call succeeded with the correct data.

**Comment by neversun** [comment]
This should fix it 5c7ea014a49c4cfecfc119aec486ff9991c648ec
