### ISSUE TITLE
Timerpicker not working in SFOS 2.0

### ISSUE THREAD

**Issue by neversun** [neversun/bodyweight-timer#5]
User nthn reported that the timepicker componenten to select minutes and seconds is not working anymore in SFOS 1.9/2.0.

I'll look into that as soon the new version is public.

**Comment by neversun** [comment]
Screenshot of TimePicker in SFOS 1.1.9.28
![20150910224950](https://cloud.githubusercontent.com/assets/9157500/9800713/da741d64-580e-11e5-8df1-6546c849d534.png)

**Comment by kimmoli** [comment]
My guess is that theme image `image://Theme/timepicker` is removed

/usr/lib/qt5/qml/Sailfish/Silica/TimePicker.qml seems to have ShaderEffect (at least in same location where the Image used to be) - check there?

**Comment by neversun** [comment]
You are right @kimmoli! They removed the image and replaced it with a shader.

Fixed with e0c4e06bbbb5d0d893ab90679a2395f4b5f6a601
